import AppKit

// MARK: clipboard etiquette (nspasteboard.org)

/// Dictation goes to the clipboard only to be pasted: clipboard managers
/// (Maccy, Raycast, Paste) are asked not to keep it in their history.
/// With [transient] false it is an ordinary copy: virtual machines and clipboard sync skip
/// transient items, so people who paste dictation into a VM need it plain.
func putDictation(_ text: String, on pb: NSPasteboard, transient: Bool = true) {
    pb.clearContents()
    let item = NSPasteboardItem()
    item.setString(text, forType: .string)
    if transient {
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.TransientType"))
        item.setData(Data(), forType: NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"))
    }
    pb.writeObjects([item])
}

/// A password copied from a password manager. Putting it back would count as a
/// fresh copy and stop the manager from clearing it, so it is not restored.
func isConcealed(_ items: [NSPasteboardItem]) -> Bool {
    let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    return items.contains { $0.types.contains(concealed) }
}

